/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[id]/subparticipation': RouteRecordInfo<
      '/[id]/subparticipation',
      '/:id/subparticipation',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/account': RouteRecordInfo<
      '/account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/addChallenge': RouteRecordInfo<
      '/addChallenge',
      '/addChallenge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/currentChallenge': RouteRecordInfo<
      '/currentChallenge',
      '/currentChallenge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/currentParticipations': RouteRecordInfo<
      '/currentParticipations',
      '/currentParticipations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/history': RouteRecordInfo<
      '/history',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderator': RouteRecordInfo<
      '/moderator',
      '/moderator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/participation/[id]': RouteRecordInfo<
      '/participation/[id]',
      '/participation/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/participationsInfinite': RouteRecordInfo<
      '/participationsInfinite',
      '/participationsInfinite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signin': RouteRecordInfo<
      '/signin',
      '/signin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[id]/subparticipation.vue': {
      routes:
        | '/[id]/subparticipation'
      views:
        | never
    }
    'src/pages/account.vue': {
      routes:
        | '/account'
      views:
        | never
    }
    'src/pages/addChallenge.vue': {
      routes:
        | '/addChallenge'
      views:
        | never
    }
    'src/pages/currentChallenge.vue': {
      routes:
        | '/currentChallenge'
      views:
        | never
    }
    'src/pages/currentParticipations.vue': {
      routes:
        | '/currentParticipations'
      views:
        | never
    }
    'src/pages/history.vue': {
      routes:
        | '/history'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/moderator.vue': {
      routes:
        | '/moderator'
      views:
        | never
    }
    'src/pages/participation/[id].vue': {
      routes:
        | '/participation/[id]'
      views:
        | never
    }
    'src/pages/participationsInfinite.vue': {
      routes:
        | '/participationsInfinite'
      views:
        | never
    }
    'src/pages/signin.vue': {
      routes:
        | '/signin'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
